INTERFACE zif_c_mdm_tool
  PUBLIC .

  CONSTANTS: BEGIN OF c_screen,
               ms_100          TYPE sy-dynnr   VALUE '0100',
               ss_101          TYPE sy-dynnr   VALUE '0101',
               ss_102          TYPE sy-dynnr   VALUE '0102',
               ss_103          TYPE sy-dynnr   VALUE '0103',
               ss_104          TYPE sy-dynnr   VALUE '0104',
               ss_105          TYPE sy-dynnr   VALUE '0105',
               ss_106          TYPE sy-dynnr   VALUE '0106',
               ss_107          TYPE sy-dynnr   VALUE '0107',
               ss_108          TYPE sy-dynnr   VALUE '0108',
               ss_109          TYPE sy-dynnr   VALUE '0109',
               ss_110          TYPE sy-dynnr   VALUE '0110',
               ss_900          TYPE sy-dynnr   VALUE '0900',
               ps_700          TYPE sy-dynnr   VALUE '0700',
               ps_800          TYPE sy-dynnr   VALUE '0800',
               name_tc_102     TYPE scrfname   VALUE 'TC_HAZDRS_MAT',
               status_100      TYPE rsfunc_txt VALUE 'STANDARD',
               status_700      TYPE rsfunc_txt VALUE 'STATUS_DYNAMIC',
               status_800      TYPE rsfunc_txt VALUE 'STATUS_MASTER_CARTON',
               title_100       TYPE rsfunc_txt VALUE 'TITLE_100',
               title_700       TYPE rsfunc_txt VALUE 'TITLE_DYNAMIC',
               ss_101_group1   TYPE char3      VALUE 'G1',
               ss_102_group1   TYPE char3      VALUE 'G1',
               ss_103_group1   TYPE char3      VALUE 'G2',
               ss_104_group1   TYPE char3      VALUE 'G5',
               ss_103_group2   TYPE char3      VALUE 'T1',
               group_t1        TYPE char3      VALUE 'T1',
               group_t2        TYPE char3      VALUE 'T2',
               group_t3        TYPE char3      VALUE 'T3',
               group_t4        TYPE char3      VALUE 'T4',
               group_t5        TYPE char3      VALUE 'T5',
               group_e1        TYPE char3      VALUE 'E1',
               group_e2        TYPE char3      VALUE 'E2',
               group_01        TYPE char3      VALUE '01',
               group_02        TYPE char3      VALUE '02',
               group_03        TYPE char3      VALUE '03',
               group_04        TYPE char3      VALUE '04',
               group_05        TYPE char3      VALUE '05',
               group_owh       TYPE char3      VALUE 'OWH',
               group_ost       TYPE char3      VALUE 'OST',
               group_uom       TYPE char3      VALUE 'UOM',
               group_icn       TYPE char3      VALUE 'ICN',
               ss_105_group1   TYPE char3      VALUE 'G3',
               ss_105_group1_c TYPE char3      VALUE 'G3C',
               ss_106_group1   TYPE char3      VALUE 'G4',
               ss_106_group1_c TYPE char3      VALUE 'G4C',
               invisible_0     TYPE char1      VALUE '0',
               invisible_1     TYPE char1      VALUE '1',
               active_0        TYPE char1      VALUE '0',
               active_1        TYPE char1      VALUE '1',
               input_0         TYPE char1      VALUE '0',
               input_1         TYPE char1      VALUE '1',
               required_1      TYPE char1      VALUE '1',
               required_2      TYPE char1      VALUE '2',
               top_ss1         TYPE string     VALUE 'TOP_BLOCK-SUB_SECTION_1',
               top_ss2         TYPE string     VALUE 'TOP_BLOCK-SUB_SECTION_2',
               top_ss3         TYPE string     VALUE 'TOP_BLOCK-SUB_SECTION_3',
               middle_ss1      TYPE string     VALUE 'MIDDLE_BLOCK-T_UNIT_OF_MEASURES',
               middle_ss2      TYPE string     VALUE 'MIDDLE_BLOCK-S_PACKSPEC_HEADER',
               mc_additional   TYPE string     VALUE 'S_MASTER_CARTON_ADITIONAL',
               lower_wrhs      TYPE string     VALUE 'LOWER_BLOCK-S_WAREHOUSE_DATA',
               lower_strg      TYPE string     VALUE 'LOWER_BLOCK-S_STORAGE_TYPE_DATA',
               lower_bin_type  TYPE string     VALUE 'LOWER_BLOCK-T_STORAGE_BIN_TYPE_SEL',
               lower_mat_text  TYPE string     VALUE 'LOWER_BLOCK-S_MATERIAL_TEXTS',
               tab1            TYPE string     VALUE 'TABS_AREA_MAT_TAB1',
               tab2            TYPE string     VALUE 'TABS_AREA_MAT_TAB2',
               tab3            TYPE string     VALUE 'TABS_AREA_MAT_TAB3',
             END OF c_screen .

  CONSTANTS: BEGIN OF c_message_severity,
               warning     TYPE symsgty VALUE 'W',
               error       TYPE symsgty VALUE 'E',
               abort       TYPE symsgty VALUE 'A',
               exit        TYPE symsgty VALUE 'X',
               success     TYPE symsgty VALUE 'S',
               information TYPE symsgty VALUE 'I',
             END OF c_message_severity.

  CONSTANTS: BEGIN OF c_class ,
               controller TYPE  seometarel-clsname VALUE 'ZCL_MDM_CONTROLLER',
             END OF c_class.
  CONSTANTS: BEGIN OF c_icon ,
               icon_message_error TYPE iconname VALUE 'ICON_MESSAGE_ERROR',
               icon_checked       TYPE iconname VALUE 'ICON_CHECKED',
               red_flag           TYPE iconname VALUE '@F1@', "icon_defect
               white_flag         TYPE iconname VALUE '@DF@', " icon_complete
               green_flag         TYPE iconname VALUE '@5Y@', "icon_release
             END OF c_icon.
  CONSTANTS: BEGIN OF c_strucutes,
               user_default          TYPE   typename VALUE 'ZSTR_USER_DEFAULT',
               storage_type_bin_type TYPE   typename VALUE 'ZSTR_STORAGE_TYPE_BIN_TYPE_SEL',
               patterns              TYPE   typename VALUE 'ZTCROSS_PATTERNS',
             END OF c_strucutes.

  CONSTANTS: BEGIN OF c_domains,
               unit     TYPE dom_ref VALUE 'ZDO_UNIT_ID',
               concstat TYPE dom_ref VALUE '/SCWM/DO_CONCSTAT',
             END OF c_domains.

  CONSTANTS: BEGIN OF c_units,
               piece        TYPE meins VALUE 'ST',
               mastercarton TYPE meins VALUE 'Z00',
               palet        TYPE meins VALUE 'PAL',
               mm           TYPE meins VALUE 'MM',
               kg           TYPE meins VALUE 'KG',
               gramm        TYPE meins VALUE 'G',
               cdm          TYPE meins VALUE 'CDM',
             END OF c_units.

  CONSTANTS: BEGIN OF c_user_command,
               enter         TYPE syst-ucomm VALUE 'ENTER',
               cont          TYPE syst-ucomm VALUE 'CONT',
               pick          TYPE syst-ucomm VALUE 'PICK',
               canc          TYPE syst-ucomm VALUE 'CANC',
               replenishment TYPE syst-ucomm VALUE 'REPL',
               ok_default    TYPE syst-ucomm VALUE 'OK_DEFAULT',
               sled          TYPE syst-ucomm VALUE 'SLED',
               save          TYPE syst-ucomm VALUE 'SAVE',
               packspec      TYPE syst-ucomm VALUE 'PACKSPEC',
               pctomc        TYPE syst-ucomm VALUE 'PCTOMC',
               mc_additon    TYPE syst-ucomm VALUE 'MC_ADDITON',
               slotting      TYPE syst-ucomm VALUE 'SLOTTING',
               alv_display   TYPE syst-ucomm VALUE 'ALV_DISPLAY',
               udemqty       TYPE syst-ucomm VALUE 'UDEMQTY',
               more01        TYPE syst-ucomm VALUE 'MORE01',
               more02        TYPE syst-ucomm VALUE 'MORE02',
               more03        TYPE syst-ucomm VALUE 'MORE03',
               more04        TYPE syst-ucomm VALUE 'MORE04',
               more05        TYPE syst-ucomm VALUE 'MORE05',
             END OF c_user_command.


  CONSTANTS: BEGIN OF c_fieldnames,
               lgnum                       TYPE fieldname   VALUE 'LGNUM',
               lgtyp                       TYPE fieldname   VALUE 'LGTYP',
               lgbkz                       TYPE fieldname   VALUE 'LGBKZ',
               lptyp                       TYPE fieldname   VALUE 'LPTYP',
               dimind                      TYPE fieldname   VALUE 'DIMIND',
               put_stra                    TYPE fieldname   VALUE 'PUT_STRA',

               text_id                     TYPE fieldname   VALUE 'TEXT_ID',
               text_type                   TYPE fieldname   VALUE 'TEXT_TYPE',
               inb_deco_text               TYPE fieldname   VALUE 'ZZ1_INB_DECO_TEXT_WHD',
               picking_text                TYPE fieldname   VALUE 'ZZ1_PICKING_TEXT_WHD',
               kep_picking_text            TYPE fieldname   VALUE 'ZZ1_KEP_PICKING_TEXT_WHD',
               sped_picking_text           TYPE fieldname   VALUE 'ZZ1_SPED_PICKING_TEXT_WHD',
               packing_text                TYPE fieldname   VALUE 'ZZ1_PACKING_TEXT_WHD',
               identtab                    TYPE fieldname   VALUE 'SELNUM',
               ean11                       TYPE fieldname   VALUE 'EAN11',
               reasoncode                  TYPE fieldname   VALUE 'REASON_CODE',
               block                       TYPE fieldname   VALUE 'BLOCK',
               tote                        TYPE fieldname   VALUE 'TOTE_QUAN',
               sled_bbd                    TYPE fieldname   VALUE 'SLED_BBD',
               indenttab02                 TYPE fieldname   VALUE 'INDENTTAB02',
               indenttab03                 TYPE fieldname   VALUE 'INDENTTAB03',
               indenttab04                 TYPE fieldname   VALUE 'INDENTTAB04',
               indenttab05                 TYPE fieldname   VALUE 'INDENTTAB05',
               template02                  TYPE fieldname   VALUE 'TEMPLATE02',
               template03                  TYPE fieldname   VALUE 'TEMPLATE03',
               template04                  TYPE fieldname   VALUE 'TEMPLATE04',
               template05                  TYPE fieldname   VALUE 'TEMPLATE05',

               langu                       TYPE fieldname   VALUE 'LANGU',
               matnr                       TYPE fieldname   VALUE 'MATNR',
               prdha                       TYPE fieldname   VALUE 'PRDHA',
               pdgnud                      TYPE fieldname   VALUE 'PDGNUD',
               ps_guid                     TYPE fieldname   VALUE 'PS_GUID',
               object_id                   TYPE fieldname   VALUE 'OBJECT_ID',
               kschl                       TYPE fieldname   VALUE 'KSCHL',
               client                      TYPE fieldname   VALUE 'CLIENT',
               pak_locid                   TYPE fieldname   VALUE 'PAK_LOCID',
               pak_locno                   TYPE fieldname   VALUE 'PAK_LOCNO',
               pak_matid                   TYPE fieldname   VALUE 'PAK_MATID',
               pak_matnr                   TYPE fieldname   VALUE 'PAK_MATNR',
               ps_psid                     TYPE fieldname   VALUE 'PS_PSID',
               ps_seq                      TYPE fieldname   VALUE 'PS_SEQ',
               created_by                  TYPE fieldname   VALUE 'CREATED_BY',
               created_on                  TYPE fieldname   VALUE 'CREATED_ON',
               date_from                   TYPE fieldname   VALUE 'DATE_FROM',
               date_to                     TYPE fieldname   VALUE 'DATE_TO',
               timestamp_from              TYPE fieldname   VALUE 'TIMESTAMP_FROM',
               timestamp_to                TYPE fieldname   VALUE 'TIMESTAMP_TO',
               kotabnr                     TYPE fieldname   VALUE 'KOTABNR',
               kvewe                       TYPE fieldname   VALUE 'KVEWE',
               release_status              TYPE fieldname   VALUE 'RELEASE_STATUS',
               kappl                       TYPE fieldname   VALUE 'KAPPL',
               mnt_ow_maint_mode_on_select TYPE fieldname   VALUE 'MNT_OW_MAINT_MODE_ON_SELECT',
               bismt40                     TYPE fieldname   VALUE 'BISMT40',
               bismt                       TYPE fieldname   VALUE 'BISMT',
               dwerk                       TYPE fieldname   VALUE 'DWERK',
               prszk_bapi                  TYPE fieldname   VALUE 'PRSZK_BAPI',
               zkprs                       TYPE fieldname   VALUE 'ZKPRS',
               taxkm                       TYPE fieldname   VALUE 'TAXKM',
               taxm1                       TYPE fieldname   VALUE 'TAXM1',
               tatyp                       TYPE fieldname   VALUE 'TATYP',
               xchpf                       TYPE fieldname   VALUE 'XCHPF',
               rvlid                       TYPE fieldname   VALUE 'RVLID',
               lwdg                        TYPE fieldname   VALUE 'LWDG',
               valto                       TYPE fieldname   VALUE 'VALTO',
               valfr                       TYPE fieldname   VALUE 'VALFR',
               template                    TYPE fieldname   VALUE 'TEMPLATE',
               tabvalue                    TYPE fieldname   VALUE 'INDENTTAB',
               description                 TYPE fieldname   VALUE 'DESCRIPTION',
               t_indenttab                 TYPE fieldname   VALUE 'T_INDENTTAB',
               is_template                 TYPE fieldname   VALUE 'IS_TEMPLATE',
               available                   TYPE fieldname   VALUE '_AVAILABLE',
               mc_additional               TYPE fieldname   VALUE 'MC_ADDITIONAL',

               prefix_zz1                  TYPE char4       VALUE 'ZZ1_',
               suffix_prd                  TYPE char4       VALUE '_PRD',
               screen_scanned_value        TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_1-SCANNED_VALUE',
               screen_entitled             TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_1-ENTITLED',
               screen_mhdrz                TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_1-MHDRZ',
               screen_pdgnud               TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_1-PDGNUD',
               screen_indenttab01          TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-INDENTTAB01',
               screen_template01           TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-TEMPLATE01',
               screen_template02           TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-TEMPLATE02',
               screen_template03           TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-TEMPLATE03',
               screen_template04           TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-TEMPLATE04',
               screen_template05           TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-TEMPLATE05',
               screen_reason_code01        TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-REASON_CODE01',
               screen_reason_code02        TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-REASON_CODE02',
               screen_reason_code03        TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-REASON_CODE03',
               screen_reason_code04        TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-REASON_CODE04',
               screen_reason_code05        TYPE dynfnam     VALUE 'GS_SCR-TOP_BLOCK-SUB_SECTION_3-REASON_CODE05',
               screen_uom_umrez            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-UMREZ',
               screen_uom_meinh            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-MEINH',
               screen_uom_pmat             TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-PMAT',
               screen_uom_ean11            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-EAN11',
               screen_uom_laeng            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-LAENG',
               screen_uom_breit            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-BREIT',
               screen_uom_hoehe            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-HOEHE',
               screen_uom_brgew            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-BRGEW',
               screen_uom_ntgew            TYPE dynfnam     VALUE 'GS_SCR-MIDDLE_BLOCK-S_UNIT_OF_MEASURES-NTGEW',

               screen_ccind                TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_WAREHOUSE_DATA-CCIND',
               screen_demqty               TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_WAREHOUSE_DATA-DEMQTY',
               screen_volind               TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_WAREHOUSE_DATA-VOLIND',
               screen_put_stra             TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_WAREHOUSE_DATA-PUT_STRA',

               screen_lgtyp                TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-LGTYP',
               screen_sectind              TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-SECTIND',
               screen_bintype              TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-BINTYPE',
               screen_repqty_dsp           TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-REPQTY_DSP',
               screen_minqty_dsp           TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-MINQTY_DSP',
               screen_maxqty_dsp           TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-MAXQTY_DSP',
               screen_tote_quan            TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-TOTE_QUAN',
               screen_zz1_maxput_stt       TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_STORAGE_TYPE_DATA-ZZ1_MAXPUT_STT',

               screen_inb_deco_text        TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_INB_DECO_TEXT_WHD',
               screen_picking_text         TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_PICKING_TEXT_WHD',
               screen_kep_picking_text     TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_KEP_PICKING_TEXT_WHD',
               screen_sped_picking_text    TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_SPED_PICKING_TEXT_WHD',
               screen_packing_text         TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_PACKING_TEXT_WHD',
               screen_vascustomer          TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_VASCUSTOMER_WHD',
               screen_vastext              TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_MATERIAL_TEXTS-ZZ1_VASTEXT_WHD',


               screen_concstat             TYPE dynfnam     VALUE 'GS_SCR-LOWER_BLOCK-S_WAREHOUSE_DATA-CONCSTAT',
               entitled                    TYPE fieldname   VALUE 'ENTITLED',
               tote_quan                   TYPE fieldname   VALUE 'ZSTR_ADDITIONAL_DATA-TOTE_QUAN',
               nonconveyable               TYPE char120     VALUE 'ZSTR_ADDITIONAL_DATA-ZZ1_NONCONVEYABLE_WHD',
             END OF c_fieldnames.

  CONSTANTS: BEGIN OF c_dictionary,
               warehouse_data            TYPE typename VALUE 'ZSTR_WAREHOUSE_DATA',
               storage_type_data         TYPE typename VALUE 'ZSTR_STORAGE_TYPE_DATA',
               storage_type_bin_type_sel TYPE typename VALUE 'ZSTR_STORAGE_TYPE_BIN_TYPE_SEL',
             END OF c_dictionary.

  CONSTANTS: BEGIN OF c_indent,
               tab01 TYPE char2 VALUE '01',
               tab02 TYPE char2 VALUE '02',
               tab03 TYPE char2 VALUE '03',
               tab04 TYPE char2 VALUE '04',
               tab05 TYPE char2 VALUE '05',
             END OF c_indent.

  CONSTANTS: BEGIN OF c_value_help,
               storage_type        TYPE shlpname VALUE '/SCWM/SH_LGTYP',
               storage_section_ind TYPE shlpname VALUE '/SCWM/SH_LGBKZ',
               bintype             TYPE shlpname VALUE '/SCWM/SH_LPTYP',
               volind              TYPE shlpname VALUE '/SCWM/SH_VOLIND',
               put_stra            TYPE shlpname VALUE '/SCWM/SH_PUT_STRA',
               identtab            TYPE shlpname VALUE 'ZSH_NUMBERS',
               reasoncode          TYPE shlpname VALUE 'ZSH_REASON_CODES',
               bulk_storage        TYPE shlpname VALUE '/SCWM/SH_BLOCK',
               material_texts      TYPE shlpname VALUE 'ZSH_CROSS_TEXTS',
               material            TYPE shlpname VALUE '/SAPAPO/MATKEY',
               pmat_only           TYPE shlpname VALUE '/SCWM/SH_PMAT_ONLY',
             END OF c_value_help.

  CONSTANTS: BEGIN OF c_hazardous,
               enq_dec_logic         TYPE esp1_func_name VALUE 'DG10N_DEQ_ENQUEUE_LOGICALLY',
               select_master         TYPE esp1_func_name VALUE 'DG20_SELECT_FROM_DB',
               start_of_the_calendar TYPE datum VALUE '00010101',
               end_of_the_calendar   TYPE datum VALUE '99991231',
               validity_area         TYPE eservlid VALUE 'ADR',
               dgtm2                 TYPE dd02l-tabname VALUE 'DGTM2',
               search                TYPE esp1_mode_type VALUE 'S',
               actype                TYPE aktyp VALUE 'D',
               picgrp                TYPE bldgr VALUE '02',
               panel                 TYPE panel VALUE 'T01',
               trtype	               TYPE trtyp VALUE 'D',
             END OF c_hazardous.

  CONSTANTS: BEGIN OF c_tabnames,
               bapi_mara     TYPE tabname VALUE 'BAPI_MARA',
               bapi_marm     TYPE tabname VALUE 'BAPI_MARM',
               bapi_marc     TYPE tabname VALUE 'BAPI_MARC',
               bapi_te_marc  TYPE tabname VALUE 'BAPI_TE_MARC',
               bapi_te_marcx TYPE tabname VALUE 'BAPI_TE_MARCX',
               bapi_te_marm  TYPE tabname VALUE 'BAPI_TE_MARM',
               bapi_te_marmx TYPE tabname VALUE 'BAPI_TE_MARMX',
             END OF c_tabnames.

  CONSTANTS: BEGIN OF c_user_parameters,
               lgn      TYPE usr05-parid VALUE '/SCWM/LGN',
               entitled	TYPE usr05-parid VALUE '/SCWM/ENTITLED',
             END OF c_user_parameters.

  CONSTANTS: BEGIN OF c_packspec,
               ps_group      TYPE  /scwm/de_ps_group VALUE 'PG01',
               level_type_01 TYPE  /scwm/de_psleveltype VALUE 'LT01',
               level_type_02 TYPE  /scwm/de_psleveltype VALUE 'LT02',
             END OF c_packspec.

  CONSTANTS: BEGIN OF c_answer,
               yes    TYPE char1 VALUE '1',
               no     TYPE char1 VALUE '2',
               cancel TYPE char1 VALUE 'A',
             END OF c_answer.

  CONSTANTS: BEGIN OF c_lock,
               exclusive TYPE tvgvi-spera VALUE 'E',
               shared    TYPE tvgvi-spera VALUE 'S',
             END OF c_lock.


  CONSTANTS: BEGIN OF c_crud,
               insert TYPE char01 VALUE 'I',
               update TYPE char01 VALUE 'U',
               delete TYPE char01 VALUE 'D',
             END OF c_crud.

  CONSTANTS: BEGIN OF c_user_param_popup,
               start_column TYPE i VALUE 10,
               start_row    TYPE i VALUE 3,
               end_column   TYPE i VALUE 98,
               end_end_row  TYPE i VALUE 12,
             END OF c_user_param_popup.


  CONSTANTS: BEGIN OF c_master_carton_popup,
               start_column TYPE i VALUE 40,
               start_row    TYPE i VALUE 10,
               end_column   TYPE i VALUE 103,
               end_end_row  TYPE i VALUE 13,
             END OF c_master_carton_popup.

  CONSTANTS: BEGIN OF c_variant,
               report_name               TYPE rsvar-report  VALUE '/SCWM/CONCEPT',
               report_name_wo_to_mon     TYPE rsvar-report  VALUE '/SCWM/SAPLWO_TO_MON',
               report_name_daily_vol     TYPE rsvar-report  VALUE 'ZCROSS_UPDATE_DAILY_VOLUME',
               variant_name              TYPE rsvar-variant VALUE 'ZMDM_',
               s_matnr                   TYPE rsscr_name    VALUE 'S_MATNR',
               select_option             TYPE rsscr_kind    VALUE 'S',
               transport_f               TYPE vari_trans    VALUE 'F',
               env_background_and_online TYPE varid_env     VALUE 'A',
               version                   TYPE varid_vers    VALUE '01',
               type_t                    TYPE char1         VALUE 'T',
               type_d                    TYPE char1         VALUE 'D',
             END OF c_variant.

  ""-->Subscreen area
  CONSTANTS: BEGIN OF c_tabs_area_mat,
               tab1 LIKE sy-ucomm VALUE 'TS1_FC1',
               tab2 LIKE sy-ucomm VALUE 'TS1_FC2',
               tab3 LIKE sy-ucomm VALUE 'TS1_FC3',
               tab4 LIKE sy-ucomm VALUE 'TS1_FC4',
             END OF c_tabs_area_mat.

  ""--<Subscreen area
  CONSTANTS: BEGIN OF c_slotting,
               report   TYPE rsvar-report VALUE '/SCWM/CONCEPT',
               weight   TYPE rsscr_name   VALUE 'P_WEIGHT',
               volume   TYPE rsscr_name   VALUE 'P_VOLUME',
               height   TYPE rsscr_name   VALUE 'P_HEIGHT',
               width    TYPE rsscr_name   VALUE 'P_WIDTH ',
               length   TYPE rsscr_name   VALUE 'P_LENGTH',
               demqty   TYPE rsscr_name   VALUE 'P_DEMQTY',
               nosoi    TYPE rsscr_name   VALUE 'P_NOSOI ',
               rsqty    TYPE rsscr_name   VALUE 'P_RSQTY ',
               putstr   TYPE rsscr_name   VALUE 'P_PUTSTR',
               remstr   TYPE rsscr_name   VALUE 'P_REMSTR',
               secind   TYPE rsscr_name   VALUE 'P_SECIND',
               bintyp   TYPE rsscr_name   VALUE 'P_BINTYP',
               maxqty   TYPE rsscr_name   VALUE 'P_MAXQTY',
               minqty   TYPE rsscr_name   VALUE 'P_MINQTY',
               repqty   TYPE rsscr_name   VALUE 'P_REPQTY',
               fixbin   TYPE rsscr_name   VALUE 'P_FIXBIN',
               demind   TYPE rsscr_name   VALUE 'P_DEMIND',
               soiind   TYPE rsscr_name   VALUE 'P_SOIIND',
               trgind   TYPE rsscr_name   VALUE 'P_TRGIND',
               save     TYPE char1 VALUE '1',
               activate TYPE char1 VALUE '2',
               dummy    TYPE char1 VALUE '3',
             END OF c_slotting.

  CONSTANTS:
    BEGIN OF c_attributes,
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',
      attr2 TYPE scx_attrname VALUE 'MV_MSGV2',
      attr3 TYPE scx_attrname VALUE 'MV_MSGV3',
      attr4 TYPE scx_attrname VALUE 'MV_MSGV4',
    END OF c_attributes ,

    BEGIN OF c_invalid_scanned_value,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '001',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_invalid_scanned_value ,
    BEGIN OF c_empty_default_value,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '002',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_empty_default_value ,
    BEGIN OF c_blocked_partner,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '003',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_blocked_partner ,
    BEGIN OF c_warehouse_number_assignment,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '004',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_warehouse_number_assignment ,

    BEGIN OF c_leadning_blanks,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '005',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_leadning_blanks ,
    BEGIN OF c_not_allowed_character,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '006',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_not_allowed_character ,

    BEGIN OF c_apo_product_number,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '007',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_apo_product_number ,
    BEGIN OF c_party_entitled_dispose,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '008',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_party_entitled_dispose ,
    BEGIN OF c_product_not_found,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '009',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_product_not_found ,

    BEGIN OF c_slotting_status_not_allowed ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '011',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_slotting_status_not_allowed ,

    BEGIN OF c_dispatch_value_not_allowed ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '012',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_dispatch_value_not_allowed ,

    BEGIN OF c_parameter_not_found ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '013',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_parameter_not_found ,

    BEGIN OF c_variant_value_not_found ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '014',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_variant_value_not_found ,

    BEGIN OF c_not_authorized ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '015',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_not_authorized ,

    BEGIN OF c_not_valid_identab_value ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '026',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_not_valid_identab_value ,

    BEGIN OF c_exists_identab_value ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '027',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_exists_identab_value ,

    BEGIN OF c_empty_master_carton_field ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '028',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_empty_master_carton_field ,

    BEGIN OF c_not_defined_default_value ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '029',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_not_defined_default_value ,

    BEGIN OF c_material_text_not_found ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '031',
      attr1 TYPE scx_attrname VALUE '',
      attr2 TYPE scx_attrname VALUE '',
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_material_text_not_found ,

    BEGIN OF c_bulk_storage_not_found ,
      msgid TYPE symsgid VALUE 'ZMC_MDM_TOOL',
      msgno TYPE symsgno VALUE '032',
      attr1 TYPE scx_attrname VALUE 'MV_MSGV1',         "#EC MG_MIS_ATT
      attr2 TYPE scx_attrname VALUE 'MV_MSGV2',         "#EC MG_MIS_ATT
      attr3 TYPE scx_attrname VALUE '',
      attr4 TYPE scx_attrname VALUE '',
    END OF c_bulk_storage_not_found,

    "<aahmedov>-190123
    BEGIN OF c_packspec_cond_type,
      zslo TYPE kschl VALUE 'ZSLO',
      ibd  TYPE kschl VALUE '0IBD',
    END OF c_packspec_cond_type.
  "<aahmedov>-190123

ENDINTERFACE.
